apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: devops
spec:
  type: NodePort  # Minikube uses NodePort by default
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 
